### ISSUE TITLE
Escrever texto para seção "Development of bioinformatics tools"

### ISSUE THREAD

**Issue by jvfe** [dalmolingroup/dalmolingroup.github.io#13]
Sugestões:
- Falar do geneplast
- Falar do Transcriptogramer

**Comment by iaradsouza1** [comment]
Talvez fosse bom tirar "desenvolvimento de ferramentas" das linhas de pesquisa e deixar tudo na aba "Tools", pq vai repetir lá.

**Comment by jvfe** [comment]
> Talvez fosse bom tirar "desenvolvimento de ferramentas" das linhas de pesquisa e deixar tudo na aba "Tools", pq vai repetir lá.

Faz sentido mas o que você acha do card linkar para a página de tools?

**Comment by iaradsouza1** [comment]
> > Talvez fosse bom tirar "desenvolvimento de ferramentas" das linhas de pesquisa e deixar tudo na aba "Tools", pq vai repetir lá.
> 
> Faz sentido mas o que você acha do card linkar para a página de tools?

Pode ser
